### ISSUE TITLE
Phlex UI Implementation

### ISSUE THREAD

**Issue by jeremyscatigna** [caley-io/caley-rails#28]
The goal here is to heavily use Phlex UI for all the UI parts of the product and contribute back to the library and the community by creating all the components we need but are not yet available in the library directly inside the library to then use them

https://github.com/PhlexUI

**Comment by wassson** [comment]
This might be better off as a project rather than an issue! We could create a whole project around hooking into Phlex, getting the gem integrated, and designing the UI/UX of the app for the initial launch. What do you think?

**Comment by jeremyscatigna** [comment]
Totally agree here

**Comment by wassson** [comment]
I don't have rights to create a project so let me know if you create one!

**Comment by bradgessler** [comment]
I've got a demo app that does this at https://github.com/rubymonolith/demo. 

It used the https://github.com/rubymonolith/superview and https://github.com/rubymonolith/superform library to accomplish 100% Phlex.

My goal is to end up with a 100% Phlex-base Rails framework called [Monolith](https://rubymonolith.com/).

If this is what you're trying to do I'd love it if you could try using it so I can get a better idea of gaps in documentation and implementation.

**Comment by wassson** [comment]
@bradgessler very interesting! I'll look into it.

**Comment by wassson** [comment]
Closing this. Will create a project with issues for creating specific components.
